### ISSUE TITLE
DFG is causing a crash WPE

### ISSUE THREAD

**Issue by bramoosterhuis** [WebPlatformForEmbedded/WPEWebKit#482] opened 2018-05-31 09:22 UTC
When loading this page: https://www.ziggogo.tv/nl.html and DFG is enabled WPE will crash. By disabling DFG the crash does not occur. The issue popped-up always but randomly in time of the loading process.

It was seen on a rpi3 with the buildroot version f52d7ba32281a4e2853c95a1a757a7402ef91861

I also noticed that once the page did load the issue didn't occur any more. So first disable DFG, load page, kill the browser, enable DFG, start the browser, load page.

**Comment by guijemont** [comment] 2018-05-31 09:39
Likely wpewebkit revision on which this was reproduced: 27f5a7cb5617ae9807df4b31c2a7a0b876c9d3ee

**Comment by guijemont** [comment] 2018-05-31 10:50
[threads.webkit.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2057857/threads.webkit.txt)
backtrace as provided by @bramoosterhuis

**Comment by guijemont** [comment] 2018-05-31 10:51
Cannot reproduce on an rpi2.

**Comment by albertd** [comment] 2018-06-14 10:01
Investigate memory pressure settings.

**Comment by guijemont** [comment] 2018-06-14 10:13
@bramoosterhuis: are you able to provide a stack trace of the crash, to get a better idea of whether it is indeed the DFG crashing or something else?

**Comment by woutermeek** [comment] 2018-07-16 19:29
This is not reproducible any more. I would like to close this ticket, unless someone can reproduce it.

**Closed** 2018-07-16 20:19 UTC
