### ISSUE TITLE
Bad performance in iframes

### ISSUE THREAD

**Issue by SteffenDE** [WebPlatformForEmbedded/WPEWebKit#433] opened 2018-01-05 18:54 UTC
I noticed that the performance of video playback is dramatically reduced when the video is inside an iframe.

Hardware: Raspberry Pi 3, WPE built using buildroot/master two days ago (raspberrypi3_wpe_defconfig).
Output mode: 1080p (not very noticeable in 720p).

config.txt
```
# Please note that this is only a sample, we recommend you to change it to fit
# your needs.
# You should override this file using a post-build script.
# See http://buildroot.org/manual.html#rootfs-custom
# and http://elinux.org/RPiconfig for a description of config.txt syntax

kernel=zImage

# To use an external initramfs file
#initramfs rootfs.cpio.gz followkernel

# Disable overscan assuming the display supports displaying the full resolution
# If the text shown on the screen disappears off the edge, comment this out
disable_overscan=1

# How much memory in MB to assign to the GPU on Pi models having
# 256, 512 or 1024 MB total memory
gpu_mem_256=128
gpu_mem_512=196
gpu_mem_1024=392

# Enable mmc by default
dtoverlay=mmc

# Fixes rpi3 ttyAMA0 serial console
dtoverlay=pi3-miniuart-bt

# Force 720p (nope, 1080p is the way to go!)
# hdmi_group=1
# hdmi_mode=4

# Overclock
# arm_freq=1350
# gpu_freq=500
# sdram_freq=500
# over_voltage=5
# avoid_warnings=1
```

I tried using overclocking, which helped a lot but didn't change the fact that the overall performance is way better without an iframe (and I prefer not to overclock the pi).

Reproduction links:
[Direct YouTube embed](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/youtube/ytdirect.html) (smooth for me)
[YouTube in iframe](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/youtube/ytframe.html) (very laggy, dropping frames)
[Direct Video embed](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/youtube/videodirect.html) (very smooth)
[Video in iframe](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/youtube/videoframe.html) (also dropping frames)

**Comment by SteffenDE** [comment] 2018-01-17 17:42
I noticed that not only the video performance is bad in iframes, but the performance in general. Using WEBKIT_SHOW_FPS I get smooth 60fps when running a CSS transform animation using wpe directly, but only 39fps in an iframe.

Comparison: [Animation outside of iframe](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/scrolling.html) vs. [Animation inside of iframe](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/scrollframe.html)

Also, when displaying a specific video in an iframe (YouTube iframe API) WPE reproducibly freezes after a while (video freezes, ~30s later audio) and is **completely** unresponsive. Sometimes, video playback starts again after a couple of seconds, but I never get the video to play perfectly.
Reproduction: https://static.steffend.me/testyt.html

**Comment by magomez** [comment] 2018-01-23 14:16
I gave a try to the video example and yes, the performance drop is noticeable (in 1080p). But I don't think it's a bug but expected behavior. Let me explain.

When drawing, the browser creates a list of layers depending on the content, and then those layers are composited (drawn with opengl) to achieve the final result.

When drawing a single video, there are 2 layers: the first one is the background of the browser and the second one is the video. For each video frame those 2 layers are painted one on top of the other, which means 60 opengl draws per second (the video is encoded to 30fps), and that works. (There are more than 60 draws cause the non-video layers are tiled, so they require more draws with smaller sizes, but this just complicates the example).

When using an iframe, there are 4 layers instead of 2: one for the background of the browser, one that is the iframe container, another one for the background of the iframe, and then the video one. This means that for each frame there are 120 draws per second (for the same 30fps video). But I'm afraid the rpi GPU is not powerful enough for this and that's why there are dropped frames. I've modified the code to test whether not drawing the layers that don't belong to the video fixed the performance drop and yes, the normal fps are achieved again.

As you say, this is not noticeable in 720p because the GPU can handle that resolution, but with 1080p it doesn't seem to be powerful enough. You can check the CPU usage and see that it's barely used, and that the GPU is the one doing the majority of the job.

**Comment by SteffenDE** [comment] 2018-01-23 21:56
Thank you for testing this, but is this/should this really be expected behavior?

I created a [test page](https://files.steffend.me/public/wpe-test-rpi3/recur_frame.html?uncache=1&depth=15) which creates recursive iframes with a specific depth.
<small>Another WebKit-Bug: Testing this in a WebKit based browser (e.g. Safari) doesn't work, because it apparently stops rendering at frame depth 4.</small>
But: I created [another test page](https://files.steffend.me/public/wpe-test-rpi3/recur_frame/frame1.html), with manually created iframes using depth 10, which works in WebKit browsers too.

The performance of WPE is not very good even when using only one single frame. For comparison, I also tested the same pages using the Android WebView on a Fire TV Stick 2 (Mali-450 MP4). Until depth 15, everything is working very smooth when using CSS animations, video performance even fine when using 25+ frames. WPE in contrast is really really sluggish when using iframes and video.
So why does Chromium (Android WebView) perform so well? I think the Mali GPU is not that much more powerful than the RPi 3's VideoCore, is it?

My use case is an application which is saved locally on the WPE device. This application is responsible for communicating with native processes (using WebSockets) and also displays error messages when the device is offline. The purpose of this local app is loading another SPA in an iframe, when the device is connected to the internet, or the content is cached locally. This SPA is responsible for displaying all the main content.
To achieve this, it has to be loaded in an iframe and communication happens via postMessage calls.
When loading the SPA using WPE directly, everything is fine (except YouTube videos using the YT iframe API, which loads the player in an iframe and has an awful performance, sometimes even [freezes WPE](https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/433#issuecomment-358383751)). But when loading the SPA using the local app (WPE -> local HTML5 app -> iframe -> SPA), all animations and videos are noticeably sluggish.

Do you know how I could circumvent creating too many layers? The empty layers of the local app aren't really needed when displaying the SPA.
**Is there a possibility to not draw layers, which are basically just empty containers?** When using a fullscreen iframe for example, the parent layers are just wasting resources.

Thank you very much for trying to help!

**Comment by SteffenDE** [comment] 2018-01-23 22:05
After thinking about it: Wouldn't it be possible for WPE to notice, when it draws empty layers? Because then it could just skip drawing them and the performance would be much better. Or am I just missing something here? Sadly, I've got no idea at all, how WebKit rendering works.

> I've modified the code to test whether not drawing the layers that don't belong to the video

Reading this does suggest that something like that would be theoretically possible. And when seeing how well the Android WebView handles iframes on low powered devices, is this maybe something Chromium does?

**Comment by hlev** [comment] 2018-02-01 21:16
> As you say, this is not noticeable in 720p because the GPU can handle that resolution, but with 1080p it doesn't seem to be powerful enough. You can check the CPU usage and see that it's barely used, and that the GPU is the one doing the majority of the job.

Unrelated to iframes, but is there any possible performance leeway in the drivers/compositors to improve full-screen 1080p playback in the browser on the RPI3? We're using the rpi-userland drivers at the moment without wayland/westeros. Would we see any performance improvements in the compositing by changing to westeros or even try the VC4 GL (if that makes sense at all)

I'm also interested in pointers in the source that need to be changed in order to:
> not drawing the layers that don't belong to the video fixed the performance drop and yes, the normal fps are achieved again.

**Comment by SteffenDE** [comment] 2018-02-02 19:03
> improve full-screen 1080p playback in the browser on the RPI3

@hlev what issues are you experiencing? Playing videos directly without using any frames is very smooth for me in 1080p (you could try overclocking the pi).

**Comment by hlev** [comment] 2018-02-04 17:22
Mild overclocking, I dialed back a bit the values that the default post-image script yields with the `--overclock-pi3` flag and don't overclock the `sdram_freq` as I read that individual Pi's can be sensitive to that.

```
arm_freq=1300
gpu_freq=500
#sdram_freq=500
over_voltage=5
```
1080p playback in the browser is not as fluid as with `omxplayer` or `gst-play`, it is a bit glitchy. I built based on the stable branch of the buildroot repo, removed bits and bobs to make the image even smaller and have upgraded the packages from the rpi repos (kernel, userland, firmware) to newer versions than in https://github.com/WebPlatformForEmbedded/buildroot/tree/stable

**Comment by albertd** [comment] 2018-11-27 09:10
@hlev the browser renders the video as a texture, this is I think creating the overhead you're seeing, I think we can't optimise this, correct @magomez. I'm closing the ticket for now.

**Closed by albertd** 2018-11-27 09:10 UTC

**Comment by hlev** [comment] 2018-11-27 11:31
Thanks @albertd. I expect some improvements moving from wpe-2016 to wpe-2017 (buildroot stable -> master) but I may be wrong. Still have a lot to explore about pipelines, different rendering paths and compositing.
