### ISSUE TITLE
[GStreamer][MSE][Youtube] During seek to unbuffered range before a buffered one, reenqueueing happens and playback becomes choppy

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#271] opened 2017-05-15 08:35 UTC
Please see logs:
https://expirebox.com/download/6660e35c3880a4849a241128c18bc61f.html

You can see that after 2017-05-15T07:51:06.833 in the attached log, WebCore::PlaybackPipeline::flush is called roughly every 2 seconds, and pipeline is switching to PAUSED state, then back to PLAYING.

This also leads to unsynchronized playback:
the observable effect are sudden audio and video jumps.

**Comment by vertexodessa** [comment] 2017-05-15 08:36
Video example with good reproduction rate: https://www.youtube.com/tv#/watch/video/control?v=VkXjvHfP3MM&resume

**Comment by Gavriliuk** [comment] 2017-05-15 09:37
The same or almost the same bugs were reproduced on the Raspberry PI with a buildroot firmware.

Immediately after seeking forward I move the position back (a little before the position of start seeking forward). After back seeking the playback works normally for a few seconds, and after that occasionally stops playing sound track (video stream is playing normally), or sometimes video stream is paused for a second (sound track is playing normally).

**Comment by vertexodessa** [comment] 2017-05-15 10:29
Might be caused by: https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/b9bf2c6edb2fd8aa4f81f57018562c2d0efee5eb

**Comment by vertexodessa** [comment] 2017-05-15 10:30
https://github.com/WebPlatformForEmbedded/WPEWebKit/issues/196

**Comment by eocanha** [comment] 2017-05-15 10:50
The commit you referenced (b9bf2c6) is a revert of the code which disables flushing. The revert was done because flushing was implemented in the commit which came next:

https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/e1d15ed3c173d683a0080d9ef3bee9d84c6ff412

Are any of the gst warnings added to PlaybackPipeline::flush() shown on your failing case?

**Comment by vertexodessa** [comment] 2017-05-15 11:19
I don't think I see any warnings, just incorrect playback behavior

**Comment by wouterlucas** [comment] 2017-05-18 18:30
@vertexodessa how often to you see this? We see that there is a difference between YouTube versions (the tiles seek vs non-tiles seek). In the tiles case (which is mostly the version I get here) it happens 1 in every 8 cases on 15m buffers. Is that the same for you or does it happen more often?

Plus can you share what the size of your MSE buffer (MSE_MAX_BUFFER_SIZE) is in your setup? Currently we're seeing the need to run with 15m for video and 25m is even better (audio:2m,video:15m,text:1m).

**Comment by vertexodessa** [comment] 2017-05-19 10:00
@Gavriliuk Alex could you please clarify reproduction rate on PI2?
@wouterlucas on XG1V3 devices it's pretty often, roughly 50% I guess. We're using the default MSE_MAX_BUFFER_SIZE values which are 30MB.

**Comment by Gavriliuk** [comment] 2017-05-19 10:07
@vertexodessa @wouterlucas 
The bug was reproduced almost always in both directions.
The rate was about 90% or more.

**Comment by wouterlucas** [comment] 2017-07-31 09:33
Fixed by the following 3 commits:
7fb21a9b680482630b1cb8ee881666b34fb8d334
3cd4d31a10ecf2664388d622190652f1541613e4
8dfa02e0439332db9f79771001fa832ddcd9da3f

Though QA reported the Yocto 1.6 image + GST backports has issues with the seek changes, these are related to the underlying GST plugins on the specific target hardware. Validated with latest GST plugins by BRCM and this issue cannot be reproduced. 

Best is to upgrade to the latest GST plugins by the BRCM manufacturer or disable re-enqueuing in the interim. Closing this issue on our and as there is nothing more to be changed on the WPE WebKit side.

**Closed by wouterlucas** 2017-07-31 09:33 UTC
