### ISSUE TITLE
Transport bar position moves back and forth when doing trick Play on Youtube

### ISSUE THREAD

**Issue by Gavriliuk** [WebPlatformForEmbedded/WPEWebKit#270] opened 2017-05-12 08:32 UTC
This bug could be easy reproduced on slow enough devices (for example, Raspberry Pi with buildroot firmware) using WPELauncher with URL http://youtube.com/tv

- Start playing the video (skip ad if it will be shown)
- Press the Up arrow twice (to hold the track bar)
- Quickly press the Left or Right arrow multiple times (to imitate a long press on the remote)

The position indicator quickly returns to the initial position just after it begins sliding aside and then continues moving to desired direction

Video examples are uploaded to youtube

Bug with forward repositioning:
https://www.youtube.com/watch?v=wDLAqbXpKMM

Bug with reverse repositioning:
https://www.youtube.com/watch?v=qhhEthn0jhU

**Comment by ravurus** [comment] 2017-05-19 11:16
Wouter, did we start analysis on this ticket?

**Comment by wouterlucas** [comment] 2017-05-19 18:46
Hi @Gavriliuk can you please elaborate what the issue is that you are seeing? I've watched your videos and see nothing abnormal. I've taken a RPI0 and trickmodes seem to work fine, it doesnt jump to position 0 for me at all and neither does it in your videos as far as I can see.

**Comment by Gavriliuk** [comment] 2017-05-23 12:52
Hi @wouterlucas 

A I described above, "The position indicator quickly returns to the initial position just after it begins sliding aside and then continues moving to desired direction".

This issue is very quick, it is well seen in real time but youtube cuts extra frames and it's hard to notice the issue during playback.

Nevertheless it can be seen on youtube too when the video is played frame by frame (enable fullscreen, put video on a pause and play it using short double clicks on the play button)

Both video examples contain the issue near the 0:02 (just on the middle of the video)

I can send you the original video fragments bu E-mail, but the issue can reproduced very easy.

**Comment by ravurus** [comment] 2017-06-02 13:44
@wouterlucas Any update on this ticket?

**Comment by eocanha** [comment] 2017-06-27 18:30
Managed to reproduce the issue on a RPI2 by enabling only one of the 4 cpu cores to lower the device cpu power. This can be achieved by adding "isolcpus=1,2,3" to /boot/cmdline.txt.

After some analysis, it seems that the high CPU load is causing some timeUpdate events to be dispatched too late (when the user has already started moving the position cursor). I have an experimental patch to avoid triggering the events when the player goes to pause automatically, but this patch could potentially cause other issues like imprecise position reporting after pause:

https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/df31bb4c3ce1452aa30231420d838b90533eed0d

Please test it and report if it solves the issue for you.

In my opinion, in order to properly prevent this, YouTube should stop listening for timeUpdate events from the moment the cursor is manually moved until the seek operation is committed.

Also, I've observed a high load in webbridge while selecting the seek position (when the cursor and the key frame gallery is shown). This might be making the situation worse and should be analyzed independently of this bug.

**Comment by albertd** [comment] 2018-11-22 09:23
@Gavriliuk @ravurus can you validate above and reopen if needed.

**Closed by albertd** 2018-11-22 09:23 UTC
