### ISSUE TITLE
Rendering error with very long animated element

### ISSUE THREAD

**Issue by SteffenDE** [WebPlatformForEmbedded/WPEWebKit#434] opened 2018-01-05 19:32 UTC
### Summary
I've noticed a weird error when having a scrolling newsticker that renders a very long list which is mostly out of view.
After a while the content just stops. But as soon as something on the page changes, the content appears again.
The element that is animated is (according to the Chrome devtools) about 60000px wide.

### Hardware and Build
I'm using a Raspberry Pi 3 with the latest buildroot build, but it's the same with all versions I tested (from buildroot and meta-wpe).

### Steps to Reproduce:
A video is available [here](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/rss-scroller/vid.mp4) and the displayed page for reproduction [here](https://s3.eu-central-1.amazonaws.com/steffend/public/wpe-test-rpi3/rss-scroller/rss.html).

### Expected Results
The ticker should scroll until all content was visible (open the example in Safari/Chrome/Firefox).

### Actual Results
The content disappears until something on the page changes.

**Comment by SteffenDE** [comment] 2018-01-17 00:23
I'm seeing a similar problem here: https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/scrolling.html

This doesn't only affect WPE, but also all other WebKit based Browsers I tested (Safari, Safari Tech Preview, WebKit Nightly, Mobile Safari), although not in the same way as seen with WPE:
[WPE master using buildroot](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/WPEScrollBug.mp4)
[Comparison: Chrome 63 / Safari 11.0.2 / Safari Tech Preview 47](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/WebKitBug.mp4)
[WebKit Nightly build r227005](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/227005.mp4)
[Mobile Safari iOS 11.2.2](https://s3.eu-central-1.amazonaws.com/steffend/public/webkitbug/MobileSafari.mp4)

Do you think I should open an issue in the main WebKit repo? I noticed the same "content-disappearing-thing" on MobileSafari too (same page), but couldn't reproduce it reliably.

As this is a basic CSS animation I think this issue is **critical**. I'm using this technique in production and therefore I am currently depending on Chromium, which is working as expected.

The animation:
```css
@keyframes scrolllistTicker {
    0% {
        transform: translate3d(0, 0%, 0);
    }
    100% {
        transform: translate3d(0, -50%, 0);
    }
}

.longlist .tickerScroll {
    animation-iteration-count: infinite;
    animation-timing-function: linear;
    animation-name: scrolllistTicker;
}
```

**Comment by SteffenDE** [comment] 2018-01-17 08:11
I reported this bug in the [WebKit Bugzilla](https://bugs.webkit.org/show_bug.cgi?id=181709), but it seems that at least the flashing issue isn't connected to the "content-disappearing" one.
"This happens because (on macOS/iOS at least), the tiles are being moved around by CoreAnimation in another thread/process; the web content process is continually evaluating tile coverage, but doesn't do a  good job when the animation loops around and the position has large discontiguous jumps." - https://bugs.webkit.org/show_bug.cgi?id=181709#c5

As CoreAnimation is iOS/macOS only, the issue with WPE seems to be another one.

**Comment by SteffenDE** [comment] 2018-02-02 19:01
As an update: this is the corresponding issue in the WebKit Bugzilla: https://bugs.webkit.org/show_bug.cgi?id=181757

**Comment by albertd** [comment] 2018-11-21 15:11
@magomez has this landed into wpe-2017 branch if so please close this ticket

**Comment by magomez** [comment] 2018-12-20 09:09
Nope, this hasn't been fixed in the 2017 branch. The issue is quite problematic and fixing it requires a big refactoring that won't happen as it is already quite old and diverged too much from current upstream code. But you can use this patch in order to workaround the issue. It's not an optimal fix but it will work while there isn't a new branch with the problem fixed.
```
diff --git a/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp b/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp
index a05733367a5..c82fe62a5cd 100644
--- a/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp
+++ b/Source/WebCore/platform/graphics/texmap/coordinated/CoordinatedGraphicsLayer.cpp
@@ -73,6 +73,7 @@ void CoordinatedGraphicsLayer::didChangeLayerState()
 void CoordinatedGraphicsLayer::didChangeAnimations()
 {
     m_shouldSyncAnimations = true;
+    setNeedsDisplay();
     notifyFlushRequired();
 }
 
@@ -1013,7 +1014,10 @@ void CoordinatedGraphicsLayer::updateContentBuffers()
 
     if (m_pendingVisibleRectAdjustment) {
         m_pendingVisibleRectAdjustment = false;
-        m_mainBackingStore->createTilesIfNeeded(transformedVisibleRect(), IntRect(0, 0, size().width(), size().height()));
+        if (selfOrAncestorHasActiveTransformAnimation())
+            m_mainBackingStore->createTilesIfNeeded(IntRect(0, 0, size().width(), size().height()), IntRect(0, 0, size().width(), size().height()));
+        else
+            m_mainBackingStore->createTilesIfNeeded(transformedVisibleRect(), IntRect(0, 0, size().width(), size().height()));
     }
 
     m_mainBackingStore->updateTileBuffers();
```

**Closed** 2018-12-20 09:13 UTC
