### ISSUE TITLE
WPE master broken with Morty build on HiKey

### ISSUE THREAD

**Issue by psivasubramanian** [WebPlatformForEmbedded/WPEWebKit#444] opened 2018-02-20 07:17 UTC
Issue:
I'm trying WPE browser (master branch) with Westeros on HiKey using Morty build, but it's not rendering any webpages even the simple local html page. This is first observed with meta-wpe master and then with morty branch when it (both) switched from WPE stable to master branch. 

Analysis:
I backtracked this issue from swapbuffers() to ThreadedCompositor::renderLayerTree() and found the cause of this issue i.e GLContext::makeContextCurrent() returning false due to eglGetCurrentContext() giving EGL_NO_CONTEXT & eglMakeCurrent() failure with error code 0x3003/EGL_BAD_ALLOC. Further I checked the flow from PlatformDisplayWPE till GLContextEGL::makeContextCurrent for pbuffer surface (fallback after egl & offscreen egl targets), all the egl calls are proper except eglMakeCurrent returning 0x3003. 

Trails:
I tried tweaking some egl configs like setting EGL_DEPTH_SIZE to 0 etc., but the symptom is not residing. Even I tried with morty's default version (1.3.1) of libepoxy. I tried disabling libepoxy by USE_LIBEPOXY=FALSE and fixing EGL/GL dependencies, still the issue is observed with WPE master (meta-wpe:morty). Then tried the working version of WPE master (7ad0f963 which worked with meta-wpe:master) with meta-wpe:morty, that itself is not working. This confirms neither using libepoxy nor WPE code changes (between master 7ad0f963 -[382e1c1](https://github.com/WebPlatformForEmbedded/WPEWebKit/commit/382e1c12994a14a9c2a3b3d2c97cb3d59e350e66)) alone causing the issue.

Logs:
root@hikey-32:~# export XDG_RUNTIME_DIR=/run/user/

root@hikey-32:~# LD_PRELOAD=/usr/lib/libwesteros_gl.so.0 westeros --renderer /usr/lib/libwesteros_render_gl.so.0 --enableCursor --display westeros-0 &

root@hikey-32:~# export WAYLAND_DISPLAY=westeros-0

root@hikey-32:~# /usr/bin/WPELauncher http://www.google.com
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
ViewBackendWesteros: running as the nested compositor
Westeros Info: checking repeating composition supported: no
Westeros Info: checking repeating composition supported: no
Westeros Warning: WstCompositorSetIsRepeater: cannot repeat with this wayland-egl: configuring nested with gl renderer
Westeros Debug: calling wl_display_create
Westeros Debug: wl_display=0xeec00470
Westeros Debug: wl_display=0xeec00470 displayName=westeros-1230-0
westeros-gl: wstGLInit: realEGLGetDisplay=(nil)
westeros-gl: wstGLInit: unable to resolve eglGetDisplay
wstRendererGLSetupEGL: eglDisplay=0x1
wstRendererGLSetupEGL: eglInitiialize: major: 1 minor: 4
wstRendererGLSetupEGL: Number of EGL configurations: 21
wstRendererGLSetupEGL: eglChooseConfig: matching configurations: 6
config 0: red: 8 green: 8 blue: 8 alpha: 8 depth: 24
choosing config 0
nativeWindow 0xeec09420
wstRendererGLSetupEGL: eglSurface 0x20000001
wstRendererGLSetupEGL: eglContext 0x40000001
eglCreateImageKHR 0xf58b5527
eglDestroyImageKHR 0xf58b556f
glEGLImageTargetTexture2DOES 0xf58bbc59
wayland-egl support expected, and is advertised by eglQueryString(eglDisplay,EGL_EXTENSIONS): proceeding to use
eglBindWaylandDisplayWL 0xf58c419d
eglUnbindWaylandDisplayWL 0xf58c41cf
eglQueryWaylandBufferWL 0xf58c4201
calling eglBindWaylandDisplayWL with eglDisplay 0x1 and wayland display 0xeec00470
have wayland-egl: 1
WstRendererCreate: module (libwesteros_render_gl.so.0) loaded and intialized
westeros-sb: WstSBInit: enter: display 0xeec00470
westeros-sb: WstSBInit: exit: display 0xeec00470 sb 0xeec09d28
westeros-simpleshell: WstSimpleShellInit: enter: display 0xeec00470
westeros-simpleshell: WstSimpleShellInit: exit: display 0xeec00470 shell 0xeec04f08
Westeros Debug: calling wl_display_run for display: westeros-1230-0
[WPEInjectedBundle] Initialized.
didClearWindowObjectForFrame
[WPELauncher] Hello InjectedBundle ...
[WPEInjectedBundle] Hello!
    array item: Test1
    array item: Test2
    array item: Test3

**Comment by psivasubramanian** [comment] 2018-06-14 07:59
One interesting observation is that WPE works if I replace the WPEWebProcess with the 2016 branch version. Actually WPE Browser is working on HiKey till the meta-wpe points to WPEWebKIt:stable and stopped working when meta-wpe (53de274c) switched to WPEWebkit:master/wpe-20170728 (382e1c12) from WPEWebkit:stable branch. So, I traversed back to meta-wpe:morty commit (029a9f5b) where it was last pointing to wpewebkit:master/wpe-20170728 (eafdc7f0) and it's working. Then I bisected between this good & bad commits of WPEWebkit recursively to locate the exact commit (5617e256) which introduced regression, but at that time meta-wpe was not following this master/wpe-20170728 branch. Another interesting thing here is the difference between this regression commit (5617e256) and it's previous commit (5e02292d) is very large (https://github.com/WebPlatformForEmbedded/WPEWebKit/compare/5e02292d52f1a9a2d69dab7c53f7022c259cea19...WebPlatformForEmbedded:5617e256ac31cc7f4d013666d4b0c47732e8bc88).

Then I enabled [WPElogs.txt](https://github.com/WebPlatformForEmbedded/WPEWebKit/files/2101332/WPElogs.txt) by exporting WEBKIT_DEBUG="Animations,Compositing, .." and also tried debugging using gdb by able to attach to running WPEWebProcess but not able to view local variables & arguments though backtrace shows only function symbols (not arguements/locals). So enabled full debug symbols by using -Og / -g, but that is giving demangler error.

**Comment by psivasubramanian** [comment] 2018-06-15 16:36
Attached WPE debug build logs as well. Tried the wpe-westeros-image on Rpi3 again now (Previously last week build with master & morty manifest/kernel v4.14), but still it kernel panics. Tried the core-image-weston on HiKey hoping to check latest WPE with Weston backend at least, but facing login issue there.

**Comment by psivasubramanian** [comment] 2018-06-20 17:12
I'm able to print all the EGL calls result when running WPE with Westeros backend on HiKey as below

root@hikey-32:~# /usr/bin/WPELauncher http://www.google.com
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
ViewBackendWesteros: running as the nested compositor
Westeros Info: checking repeating composition supported: no
Westeros Info: checking repeating composition supported: no
Westeros Warning: WstCompositorSetIsRepeater: cannot repeat with this wayland-egl: configuring nested with gl renderer
Westeros Info: waiting for compositor westeros-1157-0 to start...
Westeros Debug: calling wl_display_create
Westeros Debug: wl_display=0xea500470
Westeros Debug: wl_display=0xea500470 displayName=westeros-1157-0
westeros-gl: wstGLInit: realEGLGetDisplay=(nil)
westeros-gl: wstGLInit: unable to resolve eglGetDisplay
wstRendererGLSetupEGL: eglDisplay=0x1
wstRendererGLSetupEGL: eglInitiialize: major: 1 minor: 4
wstRendererGLSetupEGL: Number of EGL configurations: 21
wstRendererGLSetupEGL: eglChooseConfig: matching configurations: 6
config 0: red: 8 green: 8 blue: 8 alpha: 8 depth: 24
choosing config 0
nativeWindow 0xea5093d8
wstRendererGLSetupEGL: eglSurface 0x20000001
wstRendererGLSetupEGL: eglContext 0x40000001
eglCreateImageKHR 0xf1b87527
eglDestroyImageKHR 0xf1b8756f
glEGLImageTargetTexture2DOES 0xf1b8dc59
wayland-egl support expected, and is advertised by eglQueryString(eglDisplay,EGL_EXTENSIONS): proceeding to use 
eglBindWaylandDisplayWL 0xf1b9619d
eglUnbindWaylandDisplayWL 0xf1b961cf
eglQueryWaylandBufferWL 0xf1b96201
calling eglBindWaylandDisplayWL with eglDisplay 0x1 and wayland display 0xea500470
have wayland-egl: 1
WstRendererCreate: module (libwesteros_render_gl.so.0) loaded and intialized
westeros-sb: WstSBInit: enter: display 0xea500470
westeros-sb: WstSBInit: exit: display 0xea500470 sb 0xea509d08
westeros-simpleshell: WstSimpleShellInit: enter: display 0xea500470
westeros-simpleshell: WstSimpleShellInit: exit: display 0xea500470 shell 0xea504f08
Westeros Debug: calling wl_display_run for display: westeros-1157-0
Westeros Info: compositor westeros-1157-0 is started
Failed to open memory.pressure_level, error : Permission denied
Failed to open memory.pressure_level, error : Permission denied
[WPEInjectedBundle] Initialized.
GLContextEGL::createContext
GLContextEGL::createSharingContext 
GLContextEGL::createSurfacelessContext 
eglChooseConfig numberConfigsReturned 1
GLContextEGL::createWPEContext eglCreateContext error 3000
GLContextEGL::createPbufferContext 
eglChooseConfig numberConfigsReturned 1
GLContextEGL::createPbufferContext display 1, context 40000001, surface 20000001 error 3000
GLContextEGL::eglCreateContext
eglChooseConfig numberConfigsReturned 1
GLContextEGL::eglCreateContext error 3000
GLContextEGL::createWindowSurfaceWPE eglCreateWindowSurface window e9d033d8 error e9d02710
GLContextEGL::createWindowContext display 1, context 40000002, surface 20000002, error 3000
GLContextEGL::makeContextCurrent m_display.eglDisplay() 1, m_surface 20000002, m_context 40000002 eglGetError 3003
GLContextEGL::makeContextCurrent m_display.eglDisplay() 1, m_surface 20000001, m_context 40000001 eglGetError 3000

Seeing error only when eglMakeCurrent with native window (EGL_WINDOW surface type). Any idea/suggestions?

**Comment by psivasubramanian** [comment] 2018-06-21 06:43
Hi Jeff,
Thanks for commenting. Actually WPE invokes Westeros in nested mode, so it doesn't perform setupDRM as in normal mode. I already confirmed the westeros_test running successfully on nested compositor mode of westeros.

**Comment by MingyenHung** [comment] 2018-06-23 08:36
Hi @psivasubramanian ,
Your issue is very similar to mine. (eglMakeCurrent() returns error code 0x3003/EGL_BAD_ALLOC)
I traced into Mali library and found this error was caused by permission denied of some ioctls made from Mali to drm driver.
It might be helpful with my PR(https://github.com/WebPlatformForEmbedded/WPEWebKit/pull/491).

**Comment by psivasubramanian** [comment] 2018-06-25 05:52
Hi @MingyenHung , let me try this and post you. Thanks.

**Comment by psivasubramanian** [comment] 2018-06-25 12:55
Thanks @MingyenHung, it works together with other fixes combo (Disable libepoxy & enable USE_WPEWEBKIT_BACKEND_WESTEROS).

**Comment by albertd** [comment] 2018-11-22 07:48
Closing ticket as its resolved

**Closed by albertd** 2018-11-22 07:48 UTC

**Comment by psivasubramanian** [comment] 2018-11-22 10:05
Yes it's resolved, now this patch is not required as 32bit ARM Mali r7p0 release fixed it. Refer meta-96boards PRs https://github.com/96boards/meta-96boards/pull/269 or https://github.com/96boards/meta-96boards/pull/270 for using it.
